import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MockServiceWorkerProvider from "@/components/MockServiceWorkerProvider";
import { WagmiProvider } from "wagmi";
import { config } from "@/config/config";
import ReactQueryProvider from "@/components/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MockServiceWorkerProvider />
        <WagmiProvider config={config}>
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
